### ISSUE TITLE
Allow to just use template name instead of full template uid when creating service

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-robot#160]
The idea is to allow to make blueprint more easily writable.
Currently, to create a new service, you need to specify the full template uid of the template.
e.g: `github.com/zero-os/0-templates/node/0.0.1`
The goal is to be able to just specify the name of the template, so in this case `node`.

This raises 2 concerns:
- we can only allow that, if there is no overlapping in the template name between all the templates managed by the robot. If 2 templates repos contains both a node template, you'll have to specify the full uid to differentiate the two templates.
- Version is not going to be managed by client when deploying a service. So the robot will need to be able to always know which version of the template to deploy.

First concern is easy to solve, we can raise an issue if we have overlapping templates.
Regarding the second concern, this will required a bit more thinking and probably need to be done next to #151

**Comment by zaibon** [comment]
closed by #169

**Comment by ahmedelsayed-93** [comment]
### steps to reproduce 
- create zrobot and set template repos to 
```https://github.com/openvcloud/0-templates && https://github.com/zero-os/0-templates ```

- execute  this blueprint ( or any blueprint uses a template which exists in the both repos )
```yaml
services:
    - openvcloud__ovc-service-2:
        name: be-g8-3
        location: be-g8-3
        address: 'be-g8-3.demo.greenitglobe.com'
        token: '<token>'

    - account__account-service-2:
        name: test123
        openvcloud: ovc-service-2

    - vdc__vdc-service-2:
        name: test123
        account: account-service-2

    - sshkey__key-service-2:
        name: id_rsa
        dir: '/root/.ssh/'
        passphrase: <passphrase>

    - node__node-service-2:
        name: test123
        sshKey: key-service-2
        vdc: vdc-service-2

actions:
    - actions: ['install']
```

```
Traceback (most recent call last):
  File "/opt/code/github/zero-os/0-robot/zerorobot/template_collection.py", line 69, in get
    uid = TemplateUID.parse(uid)
  File "/opt/code/github/zero-os/0-robot/zerorobot/template_uid.py", line 52, in parse
    raise ValueError("format of the template uid (%s) not valid" % uid)
ValueError: format of the template uid (node) not valid

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/code/github/zero-os/0-robot/zerorobot/server/blueprints_api.py", line 16, in ExecuteBlueprint
    return handlers.ExecuteBlueprintHandler()
  File "/usr/local/lib/python3.5/dist-packages/flask_httpauth.py", line 93, in decorated
    return f(*args, **kwargs)
  File "/opt/code/github/zero-os/0-robot/zerorobot/server/handlers/ExecuteBlueprintHandler.py", line 50, in ExecuteBlueprintHandler
    _instanciate_services(service)
  File "/opt/code/github/zero-os/0-robot/zerorobot/server/handlers/ExecuteBlueprintHandler.py", line 73, in _instanciate_services
    srv = tcol.instantiate_service(service_descr['template'], service_descr['service'], service_descr.get('data', None))
  File "/opt/code/github/zero-os/0-robot/zerorobot/template_collection.py", line 148, in instantiate_service
    template = get(template)
  File "/opt/code/github/zero-os/0-robot/zerorobot/template_collection.py", line 76, in get
    uid, ','.join(templates))
TypeError: sequence item 0: expected str instance, type found
[Thu26 10:00] - pywsgi.py         :1146:j.zerorobot          - ERROR   
```

> when i used the full uid of the node template it worked

**Comment by ahmedelsayed-93** [comment]
verified 
```development : 112392f```
