### ISSUE TITLE
robot sometimes fail to start from flist

### ISSUE THREAD

**Issue by zaibon** [zero-os/0-robot#165]
I've seen this happening a few time on some node running the robot in a container

used flist is `https://hub.gig.tech/gig-autobuilder/zero-os-0-robot-autostart-0.5.1.flist`
```
In [1264]: sub.stream()
[Thu12 14:30] - GitFactory.py     :316 :j.clients.git        - INFO     - None:pull:http://github.com/zero-os/0-templates.git ->/opt/code/github/zero-os/0-templates
[Thu12 14:30] - GitFactory.py     :399 :j.clients.git        - INFO     - git clone http://github.com/zero-os/0-templates.git -> /opt/code/github/zero-os/0-templates
[Thu12 14:30] - GitFactory.py     :419 :j.clients.git        - INFO     - mkdir -p /opt/code/github/zero-os;cd /opt/code/github/zero-os;git -c http.sslVerify=false clone  -b master http://github.com/zero-os/0-templates.git /opt/code/github/zero-os/0-templates
Traceback (most recent call last):
  File "/usr/local/bin/zrobot", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/code/github/zero-os/0-robot/cmd/zrobot", line 25, in <module>
    entry_point()
  File "/opt/code/github/zero-os/0-robot/zerorobot/cli/server.py", line 66, in start
    robot.set_config_repo(config_repo, config_key)
  File "/opt/code/github/zero-os/0-robot/zerorobot/robot/robot.py", line 82, in set_config_repo
    config_repo.init(path, key)
  File "/opt/code/github/zero-os/0-robot/zerorobot/robot/config_repo.py", line 54, in init
    j.tools.configmanager.init(silent=True, configpath=path, keypath=key)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/configmanager/ConfigManager.py", line 432, in init
    j.clients.sshkey.key_get(keypath, load=True)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/clients/sshkey/SSHKeys.py", line 25, in key_get
    sshkey = self.get(instance)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/configmanager/JSBaseClassConfigs.py", line 43, in get
    return self._child_class(instance=instance, data=data, parent=self, interactive=interactive,**kwargs)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/clients/sshkey/SSHKey.py", line 23, in __init__
    parent=parent, template=TEMPLATE, interactive=interactive)
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/configmanager/JSBaseClassConfig.py", line 16, in __init__
    self._ui = j.tools.formbuilder.baseclass_get()  # is the default class
  File "/usr/lib/python3/dist-packages/js9.py", line 1709, in formbuilder
    from JumpScale9.tools.formbuilder.FormBuilder import FormBuilderFactory as FormBuilderFactory
  File "/usr/local/lib/python3.5/dist-packages/JumpScale9/tools/formbuilder/FormBuilder.py", line 3, in <module>
    import npyscreen
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/__init__.py", line 5, in <module>
    from .wgwidget                  import TEST_SETTINGS, ExhaustedTestInput, add_test_input_from_iterable, add_test_input_ch
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgwidget.py", line 5, in <module>
    import curses
  File "/usr/lib/python3.5/curses/__init__.py", line 13, in <module>
    from _curses import *
ImportError: /lib/x86_64-linux-gnu/libncursesw.so.5: symbol LINES, version NCURSES_TINFO_5.0.19991023 not defined in file libtinfo.so.5 with link time reference
[Thu12 14:30] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - /lib/x86_64-linux-gnu/libncursesw.so.5: symbol LINES, version NCURSES_TINFO_5.0.19991023 not defined in file libtinfo.so.5 with link time reference
```

**Comment by zaibon** [comment]
Duplicate of https://github.com/zero-os/0-fs/issues/27
