### ISSUE TITLE
dockerbuild.py fails with error: 'function' object has no attribute 'pull'

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-robot#174]
On a VM with **ONLY** JumpScale installed:
```bash
img_version="latest"
js_branch="development"
zrobot_branch="development"
zrobot_docker_img_builder_dir="/tmp/zero-robot_image"

mkdir -p $zrobot_docker_img_builder_dir
wget -O $zrobot_docker_img_builder_dir/dockerbuild.py https://github.com/zero-os/0-robot/raw/$zrobot_branch/utils/scripts/packages/dockerbuild.py 
cd $zrobot_docker_img_builder_dir
python3 dockerbuild.py --tag $img_version --jsbranch $js_branch --zrbranch $zrobot_branch --push PUSH --debug DEBUG
```

Result:
```python
Starting docker container ... Traceback (most recent call last):
  File "dockerbuild.py", line 80, in <module>
    _main()
  File "dockerbuild.py", line 76, in _main
    build_docker(args.tag, args.jsbranch, args.zrbranch, args.push)
  File "dockerbuild.py", line 31, in build_docker
    j.sal.docker.client.images.pull(repository="ubuntu", tag="16.04")
AttributeError: 'function' object has no attribute 'pull'
[Thu19 12:14] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - 'function' object has no attribute 'pull'
```

**Comment by zaibon** [comment]
docker is not officially supported so I'll mark this has minor priority
