### ISSUE TITLE
zrobot installation is broken on development branch

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-robot#175]
Executed on VM with JS 9.3.0 (development):
```bash
cd /opt/code/github/jumpscale
git clone git@github.com:Jumpscale/0-robot.git

cd /opt/code/github/jumpscale/0-robot
export ZROBOTBRANCH="development"
git checkout $ZROBOTBRANCH
pip install -r requirements.txt
pip install .
```

Trace back:
```python
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-zzvq9d5e/setup.py", line 71, in <module>
      'development': develop,
    File "/usr/local/lib/python3.5/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.5/dist-packages/wheel/bdist_wheel.py", line 238, in run
      self.run_command('install')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-zzvq9d5e/setup.py", line 24, in run
      msg="Running post install task")
    File "/usr/lib/python3.5/distutils/cmd.py", line 336, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "/usr/lib/python3.5/distutils/util.py", line 301, in execute
      func(*args)
    File "/tmp/pip-req-build-zzvq9d5e/setup.py", line 13, in _post_install
      j.tools.jsloader.generate()
    File "/opt/code/github/jumpscale/core9/JumpScale9/tools/loader/JSLoader.py", line 470, in generate
      self._generate()
    File "/opt/code/github/jumpscale/core9/JumpScale9/tools/loader/JSLoader.py", line 242, in _generate
      raise RuntimeError("Could not find plugin dir:%s" % path)
  RuntimeError: Could not find plugin dir:/opt/code/github/zero-os/0-robot/JumpScale9Zrobot
  [Thu19 15:36] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - Could not find plugin dir:/opt/code/github/zero-os/0-robot/JumpScale9Zrobot

  ----------------------------------------
  Failed building wheel for ZeroRobot
  Running setup.py clean for ZeroRobot
Failed to build ZeroRobot
jumpscale9lib 9.3.0 has requirement PyYAML>=3.12, but you'll have pyyaml 3.11 which is incompatible.
Installing collected packages: pycryptodome, python-jose, psutil, prometheus-client, netifaces, ZeroRobot, SQLAlchemy, speg, cson, grequests, pytz, influxdb, ovh, peewee, psycopg2, urwid, pudb, pyOpenSSL, pyblake2, pycapnp, docopt, pyte, pymux, uvloop, dnspython, python-etcd, zerotier, packet-python, blosc, ipcalc, ed25519
  Found existing installation: python-jose 1.3.2
    Uninstalling python-jose-1.3.2:
      Successfully uninstalled python-jose-1.3.2
  Found existing installation: psutil 3.4.2
Cannot uninstall 'psutil'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall
```

**Comment by iwanbk** [comment]
@yveskerwyn i updated the installation procedure yesterday

https://github.com/zero-os/0-robot/blob/development/docs/getting_started.md#install-0-robot

**Comment by yveskerwyn** [comment]
Thanks @iwanbk, I suggest that you change the  documentation to what Christophe proposed to use:
```bash
apt-get install -y libsqlite3-dev
mkdir -p /opt/code/github/zero-os
cd /opt/code/github/zero-os
git clone https://github.com/zero-os/0-robot.git
cd 0-robot
pip install -e .
```

It is the same, but better then using this `copy` command.

What is the status of an installation from JumpScale?

Do we have something like what we have for AYS: `j.tools.prefab.local.js9.atyourservice.install(branch=branch)`

-> `j.tools.prefab.local.js9.zrobot.install(branch=branch)`?

@ahussein this is ticket we had a chat about in the 0-robot group, something missing in the JumpScale installation, which I did as follows:
```bash
sudo -i
curl https://raw.githubusercontent.com/Jumpscale/bash/development/install.sh?$RANDOM > /tmp/install.sh;bash /tmp/install.sh
source ~/.bashrc
export JS9BRANCH=development
ZInstall_host_js9_full
```

**Comment by iwanbk** [comment]
> It is the same, but better then using this copy command.

Yep, right.

> What is the status of an installation from JumpScale?

No idea about it, yesterday was my first time installing the robot and use it.

**Comment by zaibon** [comment]
> Do we have something like what we have for AYS: 

There is an open issue for it: https://github.com/zero-os/0-robot/issues/163

Regarding your issue in first post, you didn't install the repo at the correct location, thus this error:
` RuntimeError: Could not find plugin dir:/opt/code/github/zero-os/0-robot/JumpScale9Zrobot`

Second error regarding psutil, my guess is or ubuntu installe psutil now and pip can't properly cope with it since it is installed from something else then pip, or there is a version conflict in this package compare to what jumpscale requires. 
@iwanbk already opened an issue about it: https://github.com/Jumpscale/core9/issues/226

**Comment by zaibon** [comment]
But all that considered, test are still passing and not broken install has been seen there. So I'm still suspecting some humand/environment error

**Comment by ahussein** [comment]
Related js9 issue is fixed and installation of 0-robot was verified on a freshly installed js9 on Ubuntu 16.04
