### ISSUE TITLE
Exception ignored error 

### ISSUE THREAD

**Issue by ahmedelsayed-93** [zero-os/0-robot#189]
i have got this error several times while connecting to zrobot, listing service and executing a blueprint 

### stack trace
```
root@ah-test:~# zrobot blueprint execute bp.yaml 
blueprint executed
list of services created:
github.com/openvcloud/0-templates/openvcloud/0.0.1 - 7bab0045-4b68-43e4-938b-72399979644f - ovc-2
list of tasks created:
[]

Exception ignored in: <function _removeHandlerRef at 0x7f1889b36e18>
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/__init__.py", line 735, in _removeHandlerRef
  File "/usr/lib/python3.5/logging/__init__.py", line 218, in _acquireLock
  File "/usr/lib/python3.5/threading.py", line 141, in acquire
  File "/usr/local/lib/python3.5/dist-packages/gevent/thread.py", line 46, in get_ident
TypeError: 'NoneType' object is not callable

```
### version
 development  fdfe7c8

**Comment by zaibon** [comment]
yeah I've seen that before, although I didn't get this anymore for quite some time.
This is due to the monkey patching, seems some stuff tried to be cleaned while they don't exist anymore.
Don't think this is really related with the robot code itself though but I'll keep it in the backlog if we one day have more info
